test:
  name: "Payment Simulation"
  description: "This benchmark scenario will use ppa transactions, to generate a database to analize bond value."
  workers:
    type: local
    number: 1
    # inicia un proceso de workers
  rounds:
    - label: writepayments
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 25
      callback: benchmarks/callbacks/foodcontrol/currency/mint.js
      arguments:
        minterOrg: farmer
        # minter: farmerMSP
        client: farmer-client-1
        endorser1Org: originator
        endorser2Org: aggregator
        endorser3Org: spv
    #- label: transfer
    #  txNumber: 500
    #  rateControl:
    #    type: fixed-rate
    #    opts:
    #      tps: 25
    #  callback: benchmarks/callbacks/foodcontrol/currency/transfer.js
    #  arguments:
    #- label: redeem
    #  txNumber: 1
    #  rateControl:
    #    type: fixed-rate
    #    opts:
    #      tps: 25
    #  callback: benchmarks/callbacks/foodcontrol/currency/redeem.js
    #  arguments:
observer:
  type: local
  interval: 1
  #type: prometheus
  #interval: 5
monitor:
  interval: 1
  type: ["docker"]
  docker:
    containers: ["all"]
  #prometheus:
  #  url: "http://prometheus:9090"
  #  push_url: "http://pushGateway:9091"
  #  metrics:
  #    ignore: [prometheus, pushGateway, cadvisor, grafana, node-exporter]
  #    include:
  #      Endorse Time (s):
  #        query: rate(endorser_propsal_duration_sum{chaincode="foodmarketplace:v1.0"}[5m])/rate(endorser_propsal_duration_count{chaincode="foodmarketplace:v1.0"}[5m])
  #        step: 1
  #        label: instance
  #        statistic: avg
